//
// Created by galvanm on 3/31/2026.
//

#ifndef SPA4_HUNT_THE_WUMPUS_LEANOSK_GALVANM_ENTITY_H
#define SPA4_HUNT_THE_WUMPUS_LEANOSK_GALVANM_ENTITY_H


class Entity {
};


#endif //SPA4_HUNT_THE_WUMPUS_LEANOSK_GALVANM_ENTITY_H