//
// Created by galvanm on 3/31/2026.
//

#ifndef SPA4_HUNT_THE_WUMPUS_LEANOSK_GALVANM_PLAYER_H
#define SPA4_HUNT_THE_WUMPUS_LEANOSK_GALVANM_PLAYER_H


class Player {
};


#endif //SPA4_HUNT_THE_WUMPUS_LEANOSK_GALVANM_PLAYER_H